### ISSUE TITLE
data directory missing when installing using pip

### ISSUE THREAD

**Issue by vishnumahamkali** [biosustain/multitfa#9]
When using pip to install, 'pip3 install git+https://github.com/biosustain/multivariate-tmfa.git', it doesn't include 'data' directory. We need 'data/component_data.npz' for 'thermo_constants.py'.

**Comment by vishnumahamkali** [comment]
@Midnighter I think Data directory import fails again 
![image](https://user-images.githubusercontent.com/45537080/100557058-4b326380-32f2-11eb-96ec-390817941020.png)

**Comment by Midnighter** [comment]
Strange, I had tested that. I'll look into it.

**Comment by Midnighter** [comment]
Should be fixed in 95f97c56a8fc0eb583b9e63b679693de61c5583b.
